[2024-01-18T23:22:54.558+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: bitcoin_data_batch_processing.submit_spark_job manual__2024-01-18T23:22:49.793102+00:00 [queued]>
[2024-01-18T23:22:54.568+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: bitcoin_data_batch_processing.submit_spark_job manual__2024-01-18T23:22:49.793102+00:00 [queued]>
[2024-01-18T23:22:54.568+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 1
[2024-01-18T23:22:54.585+0000] {taskinstance.py:1382} INFO - Executing <Task(SparkSubmitOperator): submit_spark_job> on 2024-01-18 23:22:49.793102+00:00
[2024-01-18T23:22:54.589+0000] {standard_task_runner.py:57} INFO - Started process 4225 to run task
[2024-01-18T23:22:54.592+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'bitcoin_data_batch_processing', 'submit_spark_job', 'manual__2024-01-18T23:22:49.793102+00:00', '--job-id', '31', '--raw', '--subdir', 'DAGS_FOLDER/BatchLayer_dag.py', '--cfg-path', '/tmp/tmpw1irzanz']
[2024-01-18T23:22:54.594+0000] {standard_task_runner.py:85} INFO - Job 31: Subtask submit_spark_job
[2024-01-18T23:22:54.656+0000] {task_command.py:415} INFO - Running <TaskInstance: bitcoin_data_batch_processing.submit_spark_job manual__2024-01-18T23:22:49.793102+00:00 [running]> on host 36e53310e6a3
[2024-01-18T23:22:54.757+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='bitcoin_data_batch_processing' AIRFLOW_CTX_TASK_ID='submit_spark_job' AIRFLOW_CTX_EXECUTION_DATE='2024-01-18T23:22:49.793102+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-01-18T23:22:49.793102+00:00'
[2024-01-18T23:22:54.769+0000] {base.py:73} INFO - Using connection ID 'spark_default' for task execution.
[2024-01-18T23:22:54.771+0000] {spark_submit.py:401} INFO - Spark-Submit cmd: spark-submit --master spark://172.29.0.5:7077 --name arrow-spark --queue root.default --deploy-mode client /opt/***/dags/spark_batch.py
[2024-01-18T23:22:54.943+0000] {spark_submit.py:571} INFO - /home/***/.local/lib/python3.9/site-packages/pyspark/bin/load-spark-env.sh: line 68: ps: command not found
[2024-01-18T23:23:02.884+0000] {spark_submit.py:571} INFO - 2024-01-18 23:23:02.883451: I tensorflow/core/util/port.cc:113] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
[2024-01-18T23:23:03.005+0000] {spark_submit.py:571} INFO - 2024-01-18 23:23:03.004972: I external/local_tsl/tsl/cuda/cudart_stub.cc:31] Could not find cuda drivers on your machine, GPU will not be used.
[2024-01-18T23:23:03.598+0000] {spark_submit.py:571} INFO - 2024-01-18 23:23:03.598336: E external/local_xla/xla/stream_executor/cuda/cuda_dnn.cc:9261] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
[2024-01-18T23:23:03.599+0000] {spark_submit.py:571} INFO - 2024-01-18 23:23:03.598429: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:607] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
[2024-01-18T23:23:03.727+0000] {spark_submit.py:571} INFO - 2024-01-18 23:23:03.727219: E external/local_xla/xla/stream_executor/cuda/cuda_blas.cc:1515] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
[2024-01-18T23:23:03.936+0000] {spark_submit.py:571} INFO - 2024-01-18 23:23:03.936022: I external/local_tsl/tsl/cuda/cudart_stub.cc:31] Could not find cuda drivers on your machine, GPU will not be used.
[2024-01-18T23:23:03.939+0000] {spark_submit.py:571} INFO - 2024-01-18 23:23:03.939151: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
[2024-01-18T23:23:03.939+0000] {spark_submit.py:571} INFO - To enable the following instructions: AVX2 AVX512F AVX512_VNNI FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
[2024-01-18T23:23:06.347+0000] {spark_submit.py:571} INFO - 2024-01-18 23:23:06.347081: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
[2024-01-18T23:23:12.060+0000] {spark_submit.py:571} INFO - 24/01/18 23:23:12 INFO SparkContext: Running Spark version 3.5.0
[2024-01-18T23:23:12.071+0000] {spark_submit.py:571} INFO - 24/01/18 23:23:12 INFO SparkContext: OS info Linux, 5.10.102.1-microsoft-standard-WSL2, amd64
[2024-01-18T23:23:12.071+0000] {spark_submit.py:571} INFO - 24/01/18 23:23:12 INFO SparkContext: Java version 11.0.21
[2024-01-18T23:23:12.223+0000] {spark_submit.py:571} INFO - 24/01/18 23:23:12 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
[2024-01-18T23:23:12.404+0000] {spark_submit.py:571} INFO - 24/01/18 23:23:12 INFO ResourceUtils: ==============================================================
[2024-01-18T23:23:12.404+0000] {spark_submit.py:571} INFO - 24/01/18 23:23:12 INFO ResourceUtils: No custom resources configured for spark.driver.
[2024-01-18T23:23:12.405+0000] {spark_submit.py:571} INFO - 24/01/18 23:23:12 INFO ResourceUtils: ==============================================================
[2024-01-18T23:23:12.405+0000] {spark_submit.py:571} INFO - 24/01/18 23:23:12 INFO SparkContext: Submitted application: SparkDataStreaming
[2024-01-18T23:23:12.454+0000] {spark_submit.py:571} INFO - 24/01/18 23:23:12 INFO ResourceProfile: Default ResourceProfile created, executor resources: Map(memory -> name: memory, amount: 1024, script: , vendor: , offHeap -> name: offHeap, amount: 0, script: , vendor: ), task resources: Map(cpus -> name: cpus, amount: 1.0)
[2024-01-18T23:23:12.480+0000] {spark_submit.py:571} INFO - 24/01/18 23:23:12 INFO ResourceProfile: Limiting resource is cpu
[2024-01-18T23:23:12.481+0000] {spark_submit.py:571} INFO - 24/01/18 23:23:12 INFO ResourceProfileManager: Added ResourceProfile id: 0
[2024-01-18T23:23:12.616+0000] {spark_submit.py:571} INFO - 24/01/18 23:23:12 INFO SecurityManager: Changing view acls to: ***
[2024-01-18T23:23:12.617+0000] {spark_submit.py:571} INFO - 24/01/18 23:23:12 INFO SecurityManager: Changing modify acls to: ***
[2024-01-18T23:23:12.617+0000] {spark_submit.py:571} INFO - 24/01/18 23:23:12 INFO SecurityManager: Changing view acls groups to:
[2024-01-18T23:23:12.618+0000] {spark_submit.py:571} INFO - 24/01/18 23:23:12 INFO SecurityManager: Changing modify acls groups to:
[2024-01-18T23:23:12.619+0000] {spark_submit.py:571} INFO - 24/01/18 23:23:12 INFO SecurityManager: SecurityManager: authentication disabled; ui acls disabled; users with view permissions: ***; groups with view permissions: EMPTY; users with modify permissions: ***; groups with modify permissions: EMPTY
[2024-01-18T23:23:13.052+0000] {spark_submit.py:571} INFO - 24/01/18 23:23:13 INFO Utils: Successfully started service 'sparkDriver' on port 38081.
[2024-01-18T23:23:13.105+0000] {spark_submit.py:571} INFO - 24/01/18 23:23:13 INFO SparkEnv: Registering MapOutputTracker
[2024-01-18T23:23:13.173+0000] {spark_submit.py:571} INFO - 24/01/18 23:23:13 INFO SparkEnv: Registering BlockManagerMaster
[2024-01-18T23:23:13.207+0000] {spark_submit.py:571} INFO - 24/01/18 23:23:13 INFO BlockManagerMasterEndpoint: Using org.apache.spark.storage.DefaultTopologyMapper for getting topology information
[2024-01-18T23:23:13.208+0000] {spark_submit.py:571} INFO - 24/01/18 23:23:13 INFO BlockManagerMasterEndpoint: BlockManagerMasterEndpoint up
[2024-01-18T23:23:13.217+0000] {spark_submit.py:571} INFO - 24/01/18 23:23:13 INFO SparkEnv: Registering BlockManagerMasterHeartbeat
[2024-01-18T23:23:13.270+0000] {spark_submit.py:571} INFO - 24/01/18 23:23:13 INFO DiskBlockManager: Created local directory at /tmp/blockmgr-39783b4e-2587-40fe-a21f-a52844928576
[2024-01-18T23:23:13.292+0000] {spark_submit.py:571} INFO - 24/01/18 23:23:13 INFO MemoryStore: MemoryStore started with capacity 434.4 MiB
[2024-01-18T23:23:13.319+0000] {spark_submit.py:571} INFO - 24/01/18 23:23:13 INFO SparkEnv: Registering OutputCommitCoordinator
[2024-01-18T23:23:13.569+0000] {spark_submit.py:571} INFO - 24/01/18 23:23:13 INFO JettyUtils: Start Jetty 0.0.0.0:4040 for SparkUI
[2024-01-18T23:23:13.688+0000] {spark_submit.py:571} INFO - 24/01/18 23:23:13 INFO Utils: Successfully started service 'SparkUI' on port 4040.
[2024-01-18T23:23:13.858+0000] {spark_submit.py:571} INFO - 24/01/18 23:23:13 INFO StandaloneAppClient$ClientEndpoint: Connecting to master spark://172.29.0.5:7077...
[2024-01-18T23:23:13.925+0000] {spark_submit.py:571} INFO - 24/01/18 23:23:13 INFO TransportClientFactory: Successfully created connection to /172.29.0.5:7077 after 34 ms (0 ms spent in bootstraps)
[2024-01-18T23:23:14.077+0000] {spark_submit.py:571} INFO - 24/01/18 23:23:14 INFO StandaloneSchedulerBackend: Connected to Spark cluster with app ID app-20240118232314-0001
[2024-01-18T23:23:14.081+0000] {spark_submit.py:571} INFO - 24/01/18 23:23:14 INFO StandaloneAppClient$ClientEndpoint: Executor added: app-20240118232314-0001/0 on worker-20240118223130-172.29.0.7-36307 (172.29.0.7:36307) with 2 core(s)
[2024-01-18T23:23:14.085+0000] {spark_submit.py:571} INFO - 24/01/18 23:23:14 INFO StandaloneSchedulerBackend: Granted executor ID app-20240118232314-0001/0 on hostPort 172.29.0.7:36307 with 2 core(s), 1024.0 MiB RAM
[2024-01-18T23:23:14.086+0000] {spark_submit.py:571} INFO - 24/01/18 23:23:14 INFO StandaloneAppClient$ClientEndpoint: Executor added: app-20240118232314-0001/1 on worker-20240118223130-172.29.0.8-39635 (172.29.0.8:39635) with 2 core(s)
[2024-01-18T23:23:14.086+0000] {spark_submit.py:571} INFO - 24/01/18 23:23:14 INFO StandaloneSchedulerBackend: Granted executor ID app-20240118232314-0001/1 on hostPort 172.29.0.8:39635 with 2 core(s), 1024.0 MiB RAM
[2024-01-18T23:23:14.093+0000] {spark_submit.py:571} INFO - 24/01/18 23:23:14 INFO Utils: Successfully started service 'org.apache.spark.network.netty.NettyBlockTransferService' on port 36919.
[2024-01-18T23:23:14.093+0000] {spark_submit.py:571} INFO - 24/01/18 23:23:14 INFO NettyBlockTransferService: Server created on 36e53310e6a3:36919
[2024-01-18T23:23:14.096+0000] {spark_submit.py:571} INFO - 24/01/18 23:23:14 INFO BlockManager: Using org.apache.spark.storage.RandomBlockReplicationPolicy for block replication policy
[2024-01-18T23:23:14.108+0000] {spark_submit.py:571} INFO - 24/01/18 23:23:14 INFO BlockManagerMaster: Registering BlockManager BlockManagerId(driver, 36e53310e6a3, 36919, None)
[2024-01-18T23:23:14.116+0000] {spark_submit.py:571} INFO - 24/01/18 23:23:14 INFO BlockManagerMasterEndpoint: Registering block manager 36e53310e6a3:36919 with 434.4 MiB RAM, BlockManagerId(driver, 36e53310e6a3, 36919, None)
[2024-01-18T23:23:14.118+0000] {spark_submit.py:571} INFO - 24/01/18 23:23:14 INFO BlockManagerMaster: Registered BlockManager BlockManagerId(driver, 36e53310e6a3, 36919, None)
[2024-01-18T23:23:14.120+0000] {spark_submit.py:571} INFO - 24/01/18 23:23:14 INFO BlockManager: Initialized BlockManager: BlockManagerId(driver, 36e53310e6a3, 36919, None)
[2024-01-18T23:23:14.186+0000] {spark_submit.py:571} INFO - 24/01/18 23:23:14 INFO StandaloneAppClient$ClientEndpoint: Executor updated: app-20240118232314-0001/0 is now RUNNING
[2024-01-18T23:23:14.188+0000] {spark_submit.py:571} INFO - 24/01/18 23:23:14 INFO StandaloneAppClient$ClientEndpoint: Executor updated: app-20240118232314-0001/1 is now RUNNING
[2024-01-18T23:23:14.484+0000] {spark_submit.py:571} INFO - 24/01/18 23:23:14 INFO StandaloneSchedulerBackend: SchedulerBackend is ready for scheduling beginning after reached minRegisteredResourcesRatio: 0.0
[2024-01-18T23:23:14.872+0000] {spark_submit.py:571} INFO - WARNING:cassandra.cluster:Cluster.__init__ called with contact_points specified, but no load_balancing_policy. In the next major version, this will raise an error; please specify a load-balancing policy. (contact_points = ['cassandra'], lbp = None)
[2024-01-18T23:23:15.107+0000] {spark_submit.py:571} INFO - WARNING:cassandra.cluster:Downgrading core protocol version from 66 to 65 for 172.29.0.3:9042. To avoid this, it is best practice to explicitly set Cluster(protocol_version) to the version supported by your cluster. http://datastax.github.io/python-driver/api/cassandra/cluster.html#cassandra.cluster.Cluster.protocol_version
[2024-01-18T23:23:15.112+0000] {spark_submit.py:571} INFO - WARNING:cassandra.cluster:Downgrading core protocol version from 65 to 5 for 172.29.0.3:9042. To avoid this, it is best practice to explicitly set Cluster(protocol_version) to the version supported by your cluster. http://datastax.github.io/python-driver/api/cassandra/cluster.html#cassandra.cluster.Cluster.protocol_version
[2024-01-18T23:23:15.678+0000] {spark_submit.py:571} INFO - Keyspace created successfully!
[2024-01-18T23:23:15.695+0000] {spark_submit.py:571} INFO - Table created successfully!
[2024-01-18T23:23:29.984+0000] {job.py:219} ERROR - Job heartbeat got an exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 3371, in _wrap_pool_connect
    return fn()
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 327, in connect
    return _ConnectionFairy._checkout(self)
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 894, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 493, in checkout
    rec = pool._do_get()
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/pool/impl.py", line 256, in _do_get
    return self._create_connection()
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 273, in _create_connection
    return _ConnectionRecord(self)
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 388, in __init__
    self.__connect()
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 691, in __connect
    pool.logger.debug("Error on connect(): %s", e)
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 686, in __connect
    self.dbapi_connection = connection = pool._invoke_creator(self)
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/engine/create.py", line 574, in connect
    return dialect.connect(*cargs, **cparams)
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/engine/default.py", line 598, in connect
    return self.dbapi.connect(*cargs, **cparams)
  File "/home/airflow/.local/lib/python3.9/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
psycopg2.OperationalError: could not translate host name "postgres" to address: Temporary failure in name resolution


The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/jobs/job.py", line 190, in heartbeat
    session.merge(self)
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 3056, in merge
    return self._merge(
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 3136, in _merge
    merged = self.get(
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 2853, in get
    return self._get_impl(
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 2975, in _get_impl
    return db_load_fn(
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/orm/loading.py", line 530, in load_on_pk_identity
    session.execute(
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 1716, in execute
    conn = self._connection_for_bind(bind)
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 1555, in _connection_for_bind
    return self._transaction._connection_for_bind(
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/orm/session.py", line 750, in _connection_for_bind
    conn = bind.connect()
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/future/engine.py", line 406, in connect
    return super(Engine, self).connect()
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 3325, in connect
    return self._connection_cls(self, close_with_result=close_with_result)
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 96, in __init__
    else engine.raw_connection()
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 3404, in raw_connection
    return self._wrap_pool_connect(self.pool.connect, _connection)
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 3374, in _wrap_pool_connect
    Connection._handle_dbapi_exception_noconnection(
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 2208, in _handle_dbapi_exception_noconnection
    util.raise_(
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/engine/base.py", line 3371, in _wrap_pool_connect
    return fn()
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 327, in connect
    return _ConnectionFairy._checkout(self)
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 894, in _checkout
    fairy = _ConnectionRecord.checkout(pool)
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 493, in checkout
    rec = pool._do_get()
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/pool/impl.py", line 256, in _do_get
    return self._create_connection()
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 273, in _create_connection
    return _ConnectionRecord(self)
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 388, in __init__
    self.__connect()
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 691, in __connect
    pool.logger.debug("Error on connect(): %s", e)
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/util/langhelpers.py", line 70, in __exit__
    compat.raise_(
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/util/compat.py", line 211, in raise_
    raise exception
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/pool/base.py", line 686, in __connect
    self.dbapi_connection = connection = pool._invoke_creator(self)
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/engine/create.py", line 574, in connect
    return dialect.connect(*cargs, **cparams)
  File "/home/airflow/.local/lib/python3.9/site-packages/sqlalchemy/engine/default.py", line 598, in connect
    return self.dbapi.connect(*cargs, **cparams)
  File "/home/airflow/.local/lib/python3.9/site-packages/psycopg2/__init__.py", line 122, in connect
    conn = _connect(dsn, connection_factory=connection_factory, **kwasync)
sqlalchemy.exc.OperationalError: (psycopg2.OperationalError) could not translate host name "postgres" to address: Temporary failure in name resolution

(Background on this error at: https://sqlalche.me/e/14/e3q8)
[2024-01-18T23:24:10.279+0000] {spark_submit.py:571} INFO - Traceback (most recent call last):
[2024-01-18T23:24:10.285+0000] {spark_submit.py:571} INFO - File "/opt/***/dags/spark_batch.py", line 132, in <module>
[2024-01-18T23:24:10.285+0000] {spark_submit.py:571} INFO - batch_processing()
[2024-01-18T23:24:10.286+0000] {spark_submit.py:571} INFO - File "/opt/***/dags/spark_batch.py", line 75, in batch_processing
[2024-01-18T23:24:10.286+0000] {spark_submit.py:571} INFO - historical_data = load_data_from_cassandra(spark_conn, "spark_streams", "historical_data")
[2024-01-18T23:24:10.286+0000] {spark_submit.py:571} INFO - File "/opt/***/dags/spark_batch.py", line 12, in load_data_from_cassandra
[2024-01-18T23:24:10.286+0000] {spark_submit.py:571} INFO - df = spark.read.format("org.apache.spark.sql.cassandra") \
[2024-01-18T23:24:10.286+0000] {spark_submit.py:571} INFO - File "/home/***/.local/lib/python3.9/site-packages/pyspark/python/lib/pyspark.zip/pyspark/sql/readwriter.py", line 314, in load
[2024-01-18T23:24:10.286+0000] {spark_submit.py:571} INFO - return self._df(self._jreader.load())
[2024-01-18T23:24:10.286+0000] {spark_submit.py:571} INFO - File "/home/***/.local/lib/python3.9/site-packages/pyspark/python/lib/py4j-0.10.9.7-src.zip/py4j/java_gateway.py", line 1322, in __call__
[2024-01-18T23:24:10.286+0000] {spark_submit.py:571} INFO - return_value = get_return_value(
[2024-01-18T23:24:10.286+0000] {spark_submit.py:571} INFO - File "/home/***/.local/lib/python3.9/site-packages/pyspark/python/lib/pyspark.zip/pyspark/errors/exceptions/captured.py", line 179, in deco
[2024-01-18T23:24:10.287+0000] {spark_submit.py:571} INFO - return f(*a, **kw)
[2024-01-18T23:24:10.287+0000] {spark_submit.py:571} INFO - File "/home/***/.local/lib/python3.9/site-packages/pyspark/python/lib/py4j-0.10.9.7-src.zip/py4j/protocol.py", line 326, in get_return_value
[2024-01-18T23:24:10.287+0000] {spark_submit.py:571} INFO - raise Py4JJavaError(
[2024-01-18T23:24:10.287+0000] {spark_submit.py:571} INFO - py4j.protocol.Py4JJavaError: An error occurred while calling o31.load.
[2024-01-18T23:24:10.287+0000] {spark_submit.py:571} INFO - : org.apache.spark.SparkClassNotFoundException: [DATA_SOURCE_NOT_FOUND] Failed to find the data source: org.apache.spark.sql.cassandra. Please find packages at `https://spark.apache.org/third-party-projects.html`.
[2024-01-18T23:24:10.287+0000] {spark_submit.py:571} INFO - at org.apache.spark.sql.errors.QueryExecutionErrors$.dataSourceNotFoundError(QueryExecutionErrors.scala:724)
[2024-01-18T23:24:10.287+0000] {spark_submit.py:571} INFO - at org.apache.spark.sql.execution.datasources.DataSource$.lookupDataSource(DataSource.scala:647)
[2024-01-18T23:24:10.287+0000] {spark_submit.py:571} INFO - at org.apache.spark.sql.execution.datasources.DataSource$.lookupDataSourceV2(DataSource.scala:697)
[2024-01-18T23:24:10.287+0000] {spark_submit.py:571} INFO - at org.apache.spark.sql.DataFrameReader.load(DataFrameReader.scala:208)
[2024-01-18T23:24:10.287+0000] {spark_submit.py:571} INFO - at org.apache.spark.sql.DataFrameReader.load(DataFrameReader.scala:172)
[2024-01-18T23:24:10.287+0000] {spark_submit.py:571} INFO - at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[2024-01-18T23:24:10.288+0000] {spark_submit.py:571} INFO - at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
[2024-01-18T23:24:10.288+0000] {spark_submit.py:571} INFO - at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[2024-01-18T23:24:10.288+0000] {spark_submit.py:571} INFO - at java.base/java.lang.reflect.Method.invoke(Method.java:566)
[2024-01-18T23:24:10.288+0000] {spark_submit.py:571} INFO - at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
[2024-01-18T23:24:10.288+0000] {spark_submit.py:571} INFO - at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:374)
[2024-01-18T23:24:10.288+0000] {spark_submit.py:571} INFO - at py4j.Gateway.invoke(Gateway.java:282)
[2024-01-18T23:24:10.288+0000] {spark_submit.py:571} INFO - at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
[2024-01-18T23:24:10.288+0000] {spark_submit.py:571} INFO - at py4j.commands.CallCommand.execute(CallCommand.java:79)
[2024-01-18T23:24:10.288+0000] {spark_submit.py:571} INFO - at py4j.ClientServerConnection.waitForCommands(ClientServerConnection.java:182)
[2024-01-18T23:24:10.288+0000] {spark_submit.py:571} INFO - at py4j.ClientServerConnection.run(ClientServerConnection.java:106)
[2024-01-18T23:24:10.289+0000] {spark_submit.py:571} INFO - at java.base/java.lang.Thread.run(Thread.java:829)
[2024-01-18T23:24:10.289+0000] {spark_submit.py:571} INFO - Caused by: java.lang.ClassNotFoundException: org.apache.spark.sql.cassandra.DefaultSource
[2024-01-18T23:24:10.289+0000] {spark_submit.py:571} INFO - at java.base/java.net.URLClassLoader.findClass(URLClassLoader.java:476)
[2024-01-18T23:24:10.289+0000] {spark_submit.py:571} INFO - at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:594)
[2024-01-18T23:24:10.289+0000] {spark_submit.py:571} INFO - at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:527)
[2024-01-18T23:24:10.289+0000] {spark_submit.py:571} INFO - at org.apache.spark.sql.execution.datasources.DataSource$.$anonfun$lookupDataSource$5(DataSource.scala:633)
[2024-01-18T23:24:10.289+0000] {spark_submit.py:571} INFO - at scala.util.Try$.apply(Try.scala:213)
[2024-01-18T23:24:10.289+0000] {spark_submit.py:571} INFO - at org.apache.spark.sql.execution.datasources.DataSource$.$anonfun$lookupDataSource$4(DataSource.scala:633)
[2024-01-18T23:24:10.290+0000] {spark_submit.py:571} INFO - at scala.util.Failure.orElse(Try.scala:224)
[2024-01-18T23:24:10.290+0000] {spark_submit.py:571} INFO - at org.apache.spark.sql.execution.datasources.DataSource$.lookupDataSource(DataSource.scala:633)
[2024-01-18T23:24:10.290+0000] {spark_submit.py:571} INFO - ... 15 more
[2024-01-18T23:24:10.290+0000] {spark_submit.py:571} INFO - 
[2024-01-18T23:24:12.281+0000] {taskinstance.py:1943} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/providers/apache/spark/operators/spark_submit.py", line 174, in execute
    self._hook.submit(self._application)
  File "/home/airflow/.local/lib/python3.9/site-packages/airflow/providers/apache/spark/hooks/spark_submit.py", line 502, in submit
    raise AirflowException(
airflow.exceptions.AirflowException: Cannot execute: spark-submit --master spark://172.29.0.5:7077 --name arrow-spark --queue root.default --deploy-mode client /opt/***/dags/spark_batch.py. Error code is: 1.
[2024-01-18T23:24:12.289+0000] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=bitcoin_data_batch_processing, task_id=submit_spark_job, execution_date=20240118T232249, start_date=20240118T232254, end_date=20240118T232412
[2024-01-18T23:24:12.306+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 31 for task submit_spark_job (Cannot execute: spark-submit --master spark://172.29.0.5:7077 --name arrow-spark --queue root.default --deploy-mode client /opt/***/dags/spark_batch.py. Error code is: 1.; 4225)
[2024-01-18T23:24:12.343+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2024-01-18T23:24:12.363+0000] {taskinstance.py:2784} INFO - 0 downstream tasks scheduled from follow-on schedule check
